# TODO: From command line
spring.rabbitmq.addresses: ${vcap.services.github-rabbitmq.credentials.uri}

eureka:
  client:
    serviceUrl:
      defaultZone: ${vcap.services.github-eureka.credentials.uri:http://127.0.0.1:8761}/eureka/
  instance:
    hostname: ${APPLICATION_DOMAIN}
    nonSecurePort: 80